server:
  name: go-elasticsearch-rest-api
  port: 8080

elastic_search:
  url: "http://localhost:9200"

log:
  level: info
  duration: duration
  map:
    time: "@timestamp"
    msg: message

middleware:
  log: true
  skips: /health
  request: body
  response: response
  size: size
