server:
  name: go-elasticsearch-tutorial
  port: 8080

elastic_search:
  url: "http://localhost:9200"

log:
  level: info
  map:
    time: "@timestamp"
    msg: message

middleware:
  log: true
  skips: /health
  request: request
  response: response
  size: size